### ISSUE TITLE
Removing Trend: Texas Housing Data

### ISSUE THREAD

**Issue by alexperrone** [hadley/ggplot2-book#116]
For Texas Housing data you have a function 

```
deseas <- function(x, month) {
  resid(lm(x ~ factor(month), na.action = na.exclude))
}
```

And then write "Now that we have log-transformed the data and removed the strong seasonal effects ..." No, you plotted the log-transformed data but did not store it, and this de-seasonalizes the raw data. I think you want

```
deseas <- function(x, month) {
  resid(lm(log(x) ~ factor(month), na.action = na.exclude))  # take log(x)
}
```

This is also what was performed with the `abilene` variable where the log-transformed was de-seasonalized: `mod <- lm(log(sales) ~ factor(month), data = abilene)`

This was the plot using the code currently in repository (without the `log` in `deseas`): 

![d1](https://cloud.githubusercontent.com/assets/4990236/13164103/c1bbacec-d680-11e5-9218-d2ee490a9fb3.png)

And this uses `log(x)` in `deseas`:

![d2](https://cloud.githubusercontent.com/assets/4990236/13164108/cdef0a86-d680-11e5-8c6e-2f5ad07f74d0.png)

**Comment by hadley** [comment]
Thanks @alexperrone — we've ended up removing that chapter from the next edition, since modelling is best covered elsewhere.
