### ISSUE TITLE
Dependency on broom missing

### ISSUE THREAD

**Issue by JamesHirschorn** [hadley/ggplot2-book#120]
Needs the broom package to build. However, the build does not catch the missing dependency and instead fails with an obscure error.

**Comment by hadley** [comment]
It already appears in the DESCRIPTION, so I'm not sure what the problem is.

**Comment by quantitative-technologies** [comment]
Yes, it should be closed. Though I'm not sure if this was the case almost 3 years ago when this issue was filed.
