### ISSUE TITLE
PDF maker (follow-up on issue 89)

### ISSUE THREAD

**Issue by brophyj** [hadley/ggplot2-book#121]
Hi

I am a newbie at most of this but I seem to have the same problem mentioned in issue 89 (see error below), consequently I have tried to install the framed latex package according to the instructions suggested by chuckwondo in issue 89. This now gives the following error "sudo: tlmgr: command not found".
Any suggestions would be appreciated,
## Running 'pdflatex  -interaction=batchmode -recorder  "ggplot2-book.tex"'

sh: pdflatex: command not found
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: (Pdf)LaTeX failed to generate the expected log file 'ggplot2-book.log'
Latexmk: Did not finish processing file 'ggplot2-book.tex':
   (Pdf)LaTeX failed to generate the expected log file 'ggplot2-book.log'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
make: **\* [book/ggplot2-book.pdf] Error 12

**Comment by hadley** [comment]
Unfortunately I don't have the time to provide support latex, but things are in motion that will hopefully resolve your need in other ways.
