### ISSUE TITLE
Use broom over effects?

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2-book#13]
In 4.8 Revealing uncertainty, the effects package is used to extract model components. Would you prefer to use [broom](https://github.com/dgrtwo/broom) instead?

**Comment by hadley** [comment]
I think this is now done

**Comment by cpsievert** [comment]
Looks like there is a section in toolbox that uses **effects**

https://github.com/hadley/ggplot2-book/blob/master/toolbox.rmd#revealing-uncertainty-secuncertainty
