### ISSUE TITLE
Can't build pdf [on Windows 10]

### ISSUE THREAD

**Issue by jgendrinal** [hadley/ggplot2-book#136]
When I type `make` after `make clean`, the following result pops up:

`File not found - *png`
`make: *** [book/CHAPTERS] Error 2`
`make: write error`

I've already installed make, MikTeX, pandoc, and RBuildTools on my Windows 10 system. I've used `install_deps()` already. Is there anything more I have to do?

**Comment by jgendrinal** [comment]
I tried deleting the file altogether. It didn't work

**Comment by bdengler** [comment]
I encountered a similar problem. Running `make clean` and `make` in git bash produces the following:
```
$ make clean
rm -rf book/tex
rm -rf _figures
rm -rf _cache
rm -rf *.html
rm -rf *.pdf
rm -rf book/ggplot2-book.pdf

$ make
mkdir -p book/tex
mkdir -p book/tex/_figures
mkdir -p book/tex/diagrams
cp book/ggplot2-book.tex book/tex/ggplot2-book.tex
Rscript book/render-tex.R data-manip.rmd
process_begin: CreateProcess(NULL, Rscript book/render-tex.R data-manip.rmd, ...) failed.
make (e=2): Das System kann die angegebene Datei nicht finden.
make: *** [book/tex/data-manip.tex] Error 2
```

**Comment by hadley** [comment]
Unfortunately I don't have time to help figure this out for you, but things are in motion so that hopefully you won't have to build yourself in the future.
