### ISSUE TITLE
geom_ribbon expects unrelated y value to be present

### ISSUE THREAD

**Issue by salmasian** [hadley/ggplot2-book#139]
Take this example:

```
data <- data.frame(time = 1:10, value = 17 + runif(n = 10) * 4)
ribbon.data <- data.frame(time = data$time, ymin = data$value - 2, ymax = data$value + 2)

ggplot(data, aes(x = time, y = value)) +
  geom_line() +
  geom_ribbon(data = ribbon.data, aes(x = time, ymin = ymin, ymax = ymax), alpha = 0.2)
```

It fails with the following error message: `Error in FUN(X[[i]], ...) : object 'value' not found`

If you arbitrarily define a column named `value` in the `ribbon.data`, it will work without any error. But the value you give to that column will affect the Y axis of the output.

**Comment by hadley** [comment]
This doesn't appear to be a problem with the book?

**Comment by salmasian** [comment]
Whoops, rookie mistake!

Now reported on https://github.com/tidyverse/ggplot2/issues/3364
