### ISSUE TITLE
Convert latex to markdown

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2-book#14]
The conversation in #7 is headed in this direction, so I created a new issue.

How do you want to handle figure/table referencing? There doesn't seem to be a supported Markdown equivalent for the `\ref{}`/`\label{}` combo, but I found [this hack](http://stackoverflow.com/questions/17167140/chunk-reference-using-knitr-r-markdown-and-pandoc-pander). 

I'm leaning toward leaving the latex specific referencing alone for now and wait (and hope a better alternative surfaces). What do you think?

**Comment by cpsievert** [comment]
@hadley a1e2eeb8d6397c5efba7be3eb5f364330b312c29 implements captioner in the qplot chapter. It's painfully obvious now, but I didn't realize this would remove the "click to navigate" feature. Is that a problem?

**Comment by hadley** [comment]
What's click to navigate?

**Comment by cpsievert** [comment]
What I mean by click to navigate is: if you click on, say "Figure 3.5" in the text, it will take you to that figure.

**Comment by hadley** [comment]
I think I'll get most of these as I rewrite
