### ISSUE TITLE
wesanderson colour palette library palette names altered

### ISSUE THREAD

**Issue by pecdwoodbury** [hadley/ggplot2-book#140]
Hiya,

I'm a complete novice so don't know how to upload a suggested code change yet but my PDF make failed due to the names of two palettes in the wesanderson library having been changed. I think there was originally just one for each of the relevant films but more were added so the names were suffixed with "1".

The lines below need to be changed I think in the scales.rmd file:

From:
bars + scale_fill_manual(values = wes_palette("GrandBudapest"))
bars + scale_fill_manual(values = wes_palette("Zissou"))

To:
bars + scale_fill_manual(values = wes_palette("GrandBudapest1"))
bars + scale_fill_manual(values = wes_palette("Zissou1"))

Sorry if I'm dumb and missed something!

**Comment by hadley** [comment]
Fixed by #142
