### ISSUE TITLE
Figure out how to split up scales chapter

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#150]
It feels too big at the moment. Maybe position vs. non-position would be natural?

**Comment by hadley** [comment]
Suggestions from @behrman and @skaltman:

---

Scales / controlling the mapping of data to an aesthetic

* This chapter would focus on the portions of Chapter 12 that pertain to mapping data to aesthetics, leaving the parts that discuss mapping visual elements back to the data to the next chapter.

* Sections from existing Chapter 12
  * 12.1 Introduction
  * 12.2 Modifying scales
  * 12.5 Limits
  * 12.6 Scales toolbox

Guides 

* This chapter would talk about controlling guides (adjusting labels, breaks, altering the appearance of legends, etc.).

* Sections from existing Chapter 12
  * 12.3 Guides: legends and axes
  * 12.4 Legends

This organization would also allow you to avoid having both a “Guides: legends and axes” and a “Legends” section. I think it’s a bit confusing that there are two section titles that mention legends, since legends are a type of guide. If you have a separate guides chapter, legends could just be a subsection.

**Comment by djnavarro** [comment]
fixed in #260
