### ISSUE TITLE
Proposal for the space-time chapter

### ISSUE THREAD

**Issue by djnavarro** [hadley/ggplot2-book#158]
I've been thinking about the strategy for this chapter. Before doing anything, some thoughts on structure. As it stands the chapter covers:

- Surfaces: 
    - 2d representations of 3d data via contour plots, heat maps, etc
    - mentions rgl but does not elaborate
- Maps: 
    - vector maps with geom_polygon(), and overlaying with geom_point(). 
    - mentions sp data but does not elaborate
    - raster maps with ggmap
    - chloropleths in ggplot2

Assumption: my interpretation of the new title is that "time" is not intended to refer to time series data since those drawn in the usual way time plotted on the x-axis. Instead, I am assuming that time refers to animation

As a first step, my plan is the following:

- True 3D plots by combining rayshader with ggplot2 (might have to learn it myself!)
- Extend the maps section to discuss sf data and geom_sf(). Possibly drop sp data????
- Mention the support for holes in geom_polygon() 
- Introduce gganimate() to create plots that change over time

Other things I'm thinking about:

- Possibly mention ggplotly here? Though we could do that anywhere really.
- With a slight reframing of the title, we could also talk about network visualisation briefly? Packages I thought to mention would be ggnet, ggnet2, geomnet and ggnetwork. Give an illustration of one of these? Not sure which one though!   

Does that sound like a good starting point? If so, I'll get started on this.

**Comment by hadley** [comment]
I mostly included time because I always want to write space-time, so I think we could totally drop time. Animation seems different enough to belong in a different chapter? And maybe rayshader too? Maybe a separate network chapter would be worthwhile? I could make @thomasp85 write it 😉 

Otherwise strategy sounds good - I think we should definitely drop sp in favour of sf, and it's probably worthwhile to explore more of the different types of spatial data. Not sure if there's any connection to [stars](https://github.com/r-spatial/stars/)?

**Comment by djnavarro** [comment]
Okay, I'm on it! I think the 'space-time" part made me think more in terms of breadth than depth. I'll follow your suggestions and put something together

**Comment by hadley** [comment]
TBH this could probably now be mostly just about `geom_sf()` and `coord_sf()`; I think there are enough details that there's a chapter's worth of material.

**Comment by hadley** [comment]
For raster maps, I think stars is probably the way to go, along with whatever the best way to get rasterised base layers is. (Or is there now a way to get vectorised base layers? I know that's where web mapping has been heading)
