### ISSUE TITLE
Improvements to guides

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#160]
Suggestions from @behrman and @skaltman:

12.3 Guides: legends and axes

* It might be useful to explicitly say that the guide for variables mapped to x or y is an axis, while the guide for variables mapped to color, size, etc. is a legend.

* A very small suggestion: the 12.3.1 title is “Scale title.” To sync with the table given in the 12.3 intro, it could be clearer to name it “Scale name.” The table calls only legend names “Titles.” 

12.4.3 Guide functions

* The subsection title could be more useful.
  * I really like how a lot of the section / subsection titles are useful if you're using the book table of contents as a look-up guide. For example, if you know you want to change your legend from vertical to horizontal, you could scan through and easily identify 12.4.2 Legend layout as a useful section. Many of the other section titles are like this.
  * It’s not clear from “Guide functions” what the section will discuss, especially if the reader doesn’t know or has forgotten what the guide functions do.
  * The first sentence of the section is really helpful (“The guide functions, guide_colourbar() and guide_legend(), offer additional control over the fine details of the legend”). Maybe you could draw from that sentence to create a subsection title. For example: “Detailed legend control” or “Legend details.”
* This sentence is kind of confusing: “guides() works like labs(): you can override the default guide associated with each aesthetic.”
  * If we understand correctly, the point is that guides(), like labs(), takes the name of different aesthetics (color, x, fill) as arguments. You can then override the default guide or label by assigning a value to those arguments. 
  * An example comparing labs() to guides() could be helpful.

**Comment by djnavarro** [comment]
At this point I think the key ideas here have been covered/superseded by #187 and #260. Closing for housekeeping reasons
