### ISSUE TITLE
Reorganizing scales and guides chapters

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [hadley/ggplot2-book#212]
These two chapters can be refactored into four chapters:

- Three chapters in a new part called "Scales and guides", each of which read like a reference manual:
  - _Color scales and legends_
  - _Position scales and axes_
  - _Other aesthetics_

These chapters can bring together relevant pieces from the subsections of current Scales and Guides chapters. One minor useful addition might be a suggestion for indicating `NA`s in the legend (e.g. something that says "this color means `NA`").

- One chapter in the Grammar part titled _Scales and guides_ on the general theory. This chapter can include some of the introductory material from each of the current chapters. In this chapter, might consider including the following:
  - A diagram following sentence: "Formally, each scale is a function from a region in data space (the domain of the scale) to a region in aesthetic space (the range of the scale)."
  - Mental model for when to use the shortcuts (`labs()`, `xlim()`, `ylim()`) vs. defining them in the scale functions.
  - Explaining why `scale_x_continuous()`, `scale_x_discrete()`, etc. are implemented as separate functions as opposed to just `scale_x()`: my guess is that it's because they each need a different set of arguments and different defaults. It's useful to provide a set of steps one should take as they think about how they want to customize their plot: (1) decide if the variable is continuous or discrete (2) think about how you want to transform it, etc.

**Comment by hadley** [comment]
And maybe we make a new "part" of the book called "Scales Toolbox" that would contain those three chapters, leaving a more theoretical chapter in the "The Grammar" part?

@djnavarro if that sounds ok with you, I suggest that I do the major surgery to turn the two existing chapters into four (and add the new parts), and then we work through the chapters one by one? Hopefully we won't need too much extra material, just rewriting to make everything flow again.

**Comment by djnavarro** [comment]
As it happens I'd started on this last week! There's a work-in-progress on my fork: https://github.com/djnavarro/ggplot2-book/tree/scales-toolbox. If you like I can tidy it up a bit and send a PR tomorrow? That said, if it's easier to do it yourself I'm totally fine with that too

**Comment by hadley** [comment]
Let me take a stab at it — I think I can probably quickly get it into a reasonable shape for future work, and it's really hard to review this sort of operation as a PR.

**Comment by hadley** [comment]
Ok, in now — there's still plenty of work to be done, but I think the major organisation is there, and most of the old content has been moved to the appropriate place. All the chapters will need a solid rewrite, but I think the new scales-guides theory chapter will probably need the most work.

**Comment by djnavarro** [comment]
Awesome! I'll work on the theory chapter next then :slightly_smiling_face:
