### ISSUE TITLE
New appendix section on implementing your own geom

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2-book#22]
@tdhock has a [nice write-up](http://directlabels.r-forge.r-project.org/extending-ggplot2.html) on this topic. Hadley and I agree this would be nice to have in the appendix.

**Comment by cpsievert** [comment]
I just discovered that the ggplot2 wiki has a nice write-up as well https://github.com/hadley/ggplot2/wiki/Creating-a-new-geom

**Comment by hadley** [comment]
@tdhock do you mind if I include a modified version of that text in the book? (with attribution)

**Comment by tdhock** [comment]
No I do not mind at all. Go ahead!

**Comment by hadley** [comment]
See also https://github.com/jrnold/ggthemes cc @jrnold

**Comment by hadley** [comment]
I think this is better as a ggplot2 vignette.
