### ISSUE TITLE
An issue with bulding the book

### ISSUE THREAD

**Issue by tingvan** [hadley/ggplot2-book#220]
Hi, @hadley 

I'm a new comer for ggplot2 & R.

When I try to build the book, error happens:
```
==> rmarkdown::render_site(encoding = 'UTF-8')

Error: 'bs4_book' is not an exported object from 'namespace:bookdown'
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile index.Rmd
Calls: local ... <Anonymous> -> render_new_session -> Rscript_render
Execution halted
Error: Failed to run 'render_book' in a new R session.
Execution halted

Exited with status 1.
```

How can I solve this problem?

Best,
tingvan

**Comment by hadley** [comment]
You need to install the development version of bookdown, as described in the `DESCRIPTION`. But building the book is not for the faint of heart, so I wouldn't recommend it if you're new to R.
