### ISSUE TITLE
Use lubridate?

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2-book#24]
From @ijlyttle:

Bottom of page 101:

```s
plot <- qplot(date, psavert, data = economics, geom = "line") + 
  ylab("Personal savings rate") + 
  geom_hline(xintercept = 0, colour = "grey50")

plot

plot + scale_x_date(breaks = "10 years")
plot + scale_x_date(
  limits = as.Date(c("2004-01-01", "2005-01-01")),
  labels = date_format("%Y-%m-%d")  
)
```

This brings up another point that I'll come back to later. Since the publication in 2009, we have had the introduction of `lubridate` (not to mention `dplyr`). Is it thought to update the examples accordingly (I know this is a lot of work)? Is it even a good idea?

```s
library(lubridate)

plot + scale_x_date(
  limits = as.Date(c("2004-01-01", "2005-01-01")), # can this be made easier?
  labels = stamp("2004-12-31")  
)
```

**Comment by hadley** [comment]
dplyr definitely, but I think the date time manipulation is simple enough that using base R is better (and will be more familiar to most people)
