### ISSUE TITLE
Typo in 7.2, "showing" instead of "shoving"

### ISSUE THREAD

**Issue by kitmacleod** [hadley/ggplot2-book#249]
In 7.2, I think you meant to use "showing" not "shoving" (an amazing book - thanks):
More so, most network visualizations don’t concern themselves with mapping variables to x and y aesthetics since they are concerned with shoving the network topology more than relations between two variables.

**Comment by djnavarro** [comment]
Thanks! Looks like we fixed this one when we merged #245, so I'll close this
