### ISSUE TITLE
3d graphics

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2-book#25]
From @ijlyttle:

There is a discussion (on pg 129) including the quote:

> one day I hope to add 3d graphics too.

Given that ggplot2 is now in maintenance mode, could/should this package be rephrased?

I don't know if this is the place for the larger discussion on the dangers of 3d. As I understand the arguement, 3d is a great way to hide difficult parts of your data, accidentally or otherwise. I remember one talk Hadley gave that touched on using heuristics, such as size and layering, to give the impression of 3d while still respecting the two dimensions being shown.

I don't know, as well, if this is a good place (or if there is a good place) to talk about some common graphing techniques, such as 2nd y-axis, or 3d, that (by definition) are contrary to grammar-of-graphics, and what grammar-of-graphics techniques can be used to convey the same information, perhaps not quite as concisely, but with less abiguity.

**Comment by hadley** [comment]
Removed the quote.
