### ISSUE TITLE
ggplot2 book; pitfall for the unwary reader

### ISSUE THREAD

**Issue by technocrat** [hadley/ggplot2-book#29]
On page 22 (printed), faceting is introduced and contrasted with aesthetics. The example is given of the diamonds data, which has the aesthetics "colour" and "shape" and on the following page the examples of two qplots faceted by color ~ geom ... are given

qplot(caret, data = diamonds, facets = color ~ geom ...

I spent quite a bit of time thinking that facets was a new *aesthetic* for diamonds because that is one of the ways that diamond gems are classified. It was finally a big forehead slap, but still.

BTW: the aesthetic should have the Yankee spelling *color*

**Comment by hadley** [comment]
I've changed the dataset from diamonds to mpg to avoid this problem (and for other reasons).  But the ggplot2 will always use British spelling!
