### ISSUE TITLE
Reciprocal vs reverse

### ISSUE THREAD

**Issue by kent37** [hadley/ggplot2-book#293]
This statement is incorrect:
https://github.com/hadley/ggplot2-book/blob/763f146a3bf59515d66aec8f63dcd964b42a3a40/scales-position.Rmd#L274

The plot in the previous example uses `scale_y_continuous(trans = "reciprocal")` so it does not match `scale_y_reverse()`.

Probably the previous example should use `trans="reverse"` to match .

**Comment by djnavarro** [comment]
Looks like this was covered when #260 merged. The current phrasing makes it clearer (I think) that the reciprocal transformation doesn't have a convenience scale function, whereas the reverse transformation does. I'm hoping that in the current form the reader is better able to connect the `scale_x_reverse()` remark to the example a couple of paragraphs earlier that uses the reverse transformation. I'll concede it's still less than ideal but definitely better than the text looked at the time this was opened! I'll close this now, but may want to revisit when the book gets close completion
