### ISSUE TITLE
Setup travis to run all code

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#3]

**Comment by cpsievert** [comment]
@hadley I copied the pandoc installation recipe from [rstudio/rmarkdown/.travis.yml](https://github.com/rstudio/rmarkdown/blob/master/.travis.yml), but according to [the latest build](https://travis-ci.org/hadley/ggplot2-book/builds/48918029), it can't find pandoc-citeproc. Any idea how to proceed? My other idea is to download RStudio itself and [soft link to the binaries](https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md#newer-systems-debianubuntufedora)

**Comment by hadley** [comment]
I think you need another line like

```bash
 - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc-citeproc
      -d $HOME/opt/pandoc-citeproc
```

**Comment by cpsievert** [comment]
@hadley getting closer, but now I'm running into some weird TeX errors that, for some reason, don't happen on my mac. I can try to debug, but before I do, it'd great if you could look at [the template](https://github.com/hadley/ggplot2-book/blob/master/book/ggplot2-book.tex) and see if there's anything you'd like to change.

**Comment by cpsievert** [comment]
@hadley I have a feeling people will have a hard time installing TeX requirements so maybe we should provide an html alternative?

**Comment by hadley** [comment]
Are you still having problems? Unfortunately, due to the design of the book, I think there's only so far we can go without tex.

**Comment by cpsievert** [comment]
Yep. Just wanted to make sure you didn't have plans to change the LaTeX template before trying to debug.

**Comment by cpsievert** [comment]
b2f48b3b6c4bd507a7181314367910319c3d18b9 fixes the problem. For some reason `hyperref` didn't like the `hidelinks` option (although it works on my mac). [This post](http://tex.stackexchange.com/questions/823/remove-ugly-borders-around-clickable-cross-references-and-hyperlinks) suggests putting `hidelinks` as a global option, which seems to do the trick.
