### ISSUE TITLE
Load xtable in .Rmd documents that use the package

### ISSUE THREAD

**Issue by jflanaga** [hadley/ggplot2-book#30]
I mentioned this on a different issue, but I thought I would put it here to make sure it got caught. With commit 2c1c0a2, there was a switch from `pander::pandoc.table` to `xtable` for creating tables. However, `xtable`is not loaded into the session in the .Rmd files, and I believe that this causes the document not to be knitted properly in any chapter that calls `xtable`. I would make the changes myself and make a pull request, but when I made the changes it did something odd and the `make` won't work properly, so I thought I would just make it an issue.

**Comment by cpsievert** [comment]
See reply [here](https://github.com/hadley/ggplot2-book/issues/17#issuecomment-72519536)
