### ISSUE TITLE
Unclear phrasing in Grobs of Grid in 5 minutes

### ISSUE THREAD

**Issue by BrianDiggs** [hadley/ggplot2-book#316]
https://github.com/hadley/ggplot2-book/blob/01734fa9361eb1ce6ff954d77fa2d6c01f10430b/ext-springs.Rmd#L613

The beginning of this paragraph reads: "You can create a new grob new grob classes with the ..." Exactly what is meant by "a new grob new grob classes" is not clear.

**Comment by hadley** [comment]
Fixed in #360
