### ISSUE TITLE
underscores in figure captions break latex output

### ISSUE THREAD

**Issue by stevelinberg** [hadley/ggplot2-book#319]
When rendering to latex, the caption for figure 17.1 fails to render because it contains unescaped underscores (in "`facet_grid()`" and "`facet_wrap()`"). A fix is to create the caption above the block and reference it in the figure, which causes it to be correctly escaped when rendering to either latex or HTML, as described in the "[Text References](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references
)" section of [Authoring Books with R Markdown](https://bookdown.org/).

Also submitting a PR with this fix.

**Comment by djnavarro** [comment]
closing the issue per discussion in #320.
