### ISSUE TITLE
Saving plots to .rds files

### ISSUE THREAD

**Issue by teunbrand** [hadley/ggplot2-book#344]
The advice given in this section of the book:

https://github.com/hadley/ggplot2-book/blob/bf758abd4270b60d4ceb4e7f3d3bec73193526fa/getting-started.Rmd#L526-L533

Is being called a 'flawed workflow' in https://github.com/tidyverse/ggplot2/issues/3994#issuecomment-642051735 and complicates between-version compatability as mentioned here: https://github.com/tidyverse/ggplot2/issues/3994#issuecomment-1142116587. I think it might be best to omit this advice altogether.

**Comment by hadley** [comment]
Oh yeah, that's definitely a DON'T DO.

**Comment by djnavarro** [comment]
ooh, yeah, I'll fix that one now!

**Comment by teunbrand** [comment]
Thanks!
