### ISSUE TITLE
Strange reference hover

### ISSUE THREAD

**Issue by psychelzh** [hadley/ggplot2-book#353]
See the screenshot, which is kind of messy:

![image](https://user-images.githubusercontent.com/13306020/217821599-8ffd4ac4-a862-4d9a-8ebd-d482305c2e20.png)

The code is seemingly not problematic, but maybe the style can be enhanced?

https://github.com/hadley/ggplot2-book/blob/904d33b9583ea09345b953438960446d9bbeac73/themes.Rmd#L89

**Comment by djnavarro** [comment]
Yeah, that's definitely something we'll have to fix. My feeling is these kinds of stylistic and formatting issues are something we'll look at after we port the code from bookdown to quarto

**Comment by psychelzh** [comment]
Confirmed this is solved now.
