### ISSUE TITLE
Role of touch in the makefile

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#38]
@cpsievert can you explain why you're using touch in the makefile? This seems like an anti-pattern to me, because it will force recomputation even when the source file hasn't changed

**Comment by cpsievert** [comment]
I think [this one](https://github.com/hadley/ggplot2-book/blob/master/Makefile#L37-L38) makes sense since if we change the compilation method, that should probably apply to all chapters, but we could probably get rid of the other uses.

**Comment by hadley** [comment]
Oh got it

**Comment by cpsievert** [comment]
3bff8dd removes unnecessary `touch` commands, and I suppose the one I reference above could be removed as well with a clever use of `file.mtime()` inside `render-tex.R`, but I'd like to keep the logic somewhat simple...

**Comment by hadley** [comment]
Perfect - thanks!
