### ISSUE TITLE
More makefile woes

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#41]
I'm seeing multiple calls to

```
Rscript render-tex.R data-transformation.rmd data.rmd introduction.rmd qplot.rmd
Rscript render-tex.R data-transformation.rmd data.rmd introduction.rmd qplot.rmd
```

Any ideas?

**Comment by cpsievert** [comment]
Huh, I wasn't able to replicate this, but I have a feeling it was due to the rule I just removed in acf8369.

I think it's better for development purposes not to worry about re-rendering all the chapters if `render-tex.R` has been modified. Does that sound reasonable?

**Comment by cpsievert** [comment]
Hold on, I think I just stumbled across the problem...

**Comment by cpsievert** [comment]
I think `make` was calling `Rscript` for each chapter that had become invalidated (which was not my intention).

**Comment by cpsievert** [comment]
Now you should see something like

```
Rscript render-tex.R data-transformation.rmd 
Rscript render-tex.R data.rmd 
Rscript render-tex.R introduction.rmd 
Rscript render-tex.R qplot.rmd
```

Instead of 

```
Rscript render-tex.R data-transformation.rmd data.rmd introduction.rmd qplot.rmd
Rscript render-tex.R data-transformation.rmd data.rmd introduction.rmd qplot.rmd
Rscript render-tex.R data-transformation.rmd data.rmd introduction.rmd qplot.rmd
Rscript render-tex.R data-transformation.rmd data.rmd introduction.rmd qplot.rmd
```

**Comment by hadley** [comment]
great, thanks!
