### ISSUE TITLE
Common code options at top of each file

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#42]
Rather than setting options in `render-tex.R` (which are only included when turned into a pdf), I think it would be better for each chapter to source a common file at the top. This could set common options, a seed and load common packages.

It also might be better to move the captioner code in here - however I don't quite understand what `bumper()` is doing.

**Comment by cpsievert** [comment]
[`bumper()`](https://github.com/hadley/ggplot2-book/blob/9ec4ebcd21a02dbbc9eca24b71193b8941cf2c7f/render-tex.R#L58-L71) is meant to ensure correct section numbering regardless of which chapters are rendered (and in which order)

**Comment by hadley** [comment]
Oh I see - I think it would be better just to maintain a static chapter name to section number look up table. Then that can be included at the start of each chapter.

**Comment by hadley** [comment]
Getting this as I go. I doubt we'll need captioner once I'm done

**Comment by cpsievert** [comment]
@hadley with https://github.com/hadley/ggplot2-book/commit/ea62076b5e544fb5f78d79b8ec695946697e4f6a, I changed from `bumper()`to a lookup in a static csv file.
