### ISSUE TITLE
Turn caching on?

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#43]
It would be useful to enable caching when building individual chapters

**Comment by cpsievert** [comment]
I can look into this

**Comment by cpsievert** [comment]
Unless I'm missing something, I don't think this will be possible on Travis.

Caching is only available for private repos and container-based builds. 

Container-based builds do not allow use of `sudo` (which I think we need). It looks like [caching ubuntu packages](http://docs.travis-ci.com/user/caching/#Caching-Ubuntu-packages) would be a work around, but again, that is only available for private repos

**Comment by hadley** [comment]
Sorry, I meant knitr caching for local builds.

**Comment by cpsievert** [comment]
Oh, right, that'd be useful, perhaps we can just add that as a global option [here](https://github.com/hadley/ggplot2-book/blob/90987f445e6614b798f381044cad86a149d6cd85/render-tex.R#L26-L36)? And then add `cache/` to `.gitignore`?

**Comment by hadley** [comment]
Done
