### ISSUE TITLE
Use native R build?

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2-book#48]
@hadley it looks like a native R build [fails since `devtools::install_deps(dependencies = TRUE)` fails when there is no DESCRIPTION file](https://travis-ci.org/hadley/ggplot2-book/builds/62442268#L2133).

Maybe it makes sense to add a check for a DESCRIPTION, and if none exists, exit without error (to support projects such as this one)? cc @craigcitro

In the meantime, I'll go back to the old r-travis approach to avoid calling `devtools::install_deps()`

BTW, I think we've been displaying a false positive build, which I identified in ee3d5cb7dce6beb47e9f4edb33d364a28c215b11. I'll get on that right away.

**Comment by hadley** [comment]
Alternatively, maybe we should include a description file? That would make it easier for users of the repo to get all the packages they need

**Comment by cpsievert** [comment]
Sure, that makes sense

**Comment by cpsievert** [comment]
Alright, that worked like a charm and the build is passing now
