### ISSUE TITLE
modelling.rmd has an Rscript error when I try to build the book

### ISSUE THREAD

**Issue by jowens** [hadley/ggplot2-book#52]
I will be happy to leave more info if desired; I am not an experienced R user at all. Error is:

````
Rscript render-tex.R modelling.rmd


processing file: modelling.rmd

Attaching package: 'dplyr'

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Quitting from lines 176-183 (modelling.rmd)
Error in resid(mod) : object 'mod' not found
Calls: mapply ... lapply -> eval.quoted -> lapply -> FUN -> eval -> resid
In addition: Warning messages:
1: In loop_apply(n, do.ply) :
  Removed 1192 rows containing missing values (geom_path).
2: In loop_apply(n, do.ply) :
  Removed 1192 rows containing missing values (geom_path).
Execution halted
make: *** [book/tex/modelling.tex] Error 1
````

Here's the offending lines, which look to me to actually define mod:

````
```{r, fig.keep="hold"}
abilene <- tx %>% filter(city == "Abilene")
ggplot(abilene, aes(date, log(sales))) + 
  geom_line()

mod <- lm(log(sales) ~ factor(month), data = abilene)
ggplot(abilene, aes(date, resid(mod))) + 
  geom_line()
````

````
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin14.3.0 (64-bit)
````

**Comment by hadley** [comment]
This is some weird plyr bug that I know about but can't reliably reproduce :(  If you run it again, it'll probably go away.

**Comment by jowens** [comment]
Well, it happens every time for me; can't get past it, alas. Glad to know it's not me being a moron though!

**Comment by hadley** [comment]
What OS are you using?

**Comment by jowens** [comment]
OS X 10.10.3, with R 3.1.2 installed via Macports.

I am totally willing to nuke my entire R library and start over if {you think that would help, you think it would help you debug}.

**Comment by hadley** [comment]
No, that won't help unfortunately

**Comment by xcix** [comment]
I have the same error on Debian 3.2.0-4-amd64
R version 3.1.1 (2014-07-10) -- "Sock it to Me"

**Comment by shiyuangu** [comment]
Same problem here for R 3.1.3
------------------------------------------------
platform       i686-pc-linux-gnu           
arch           i686                        
os             linux-gnu                   
system         i686, linux-gnu             
status                                     
major          3                           
minor          1.3                         
year           2015                        
month          03                          
day            09                          
svn rev        67962                       
language       R                           
version.string R version 3.1.3 (2015-03-09)
nickname       Smooth Sidewalk

**Comment by jianxinwang** [comment]
Under Unbuntu 14.04, I got the same error message if I just type "make", but the problem went away by running make with multi-proccesor, e.g. "make -j 8".
