### ISSUE TITLE
Environment problems (knitr vs. make)

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#53]
`qplot.rmd` works if I knit it in RStudio, but if I build it with the make file, I get an error about the `year()` function defined in line 430. Any ideas why the environments might be different between the two ways of building?

**Comment by cpsievert** [comment]
Hmm, maybe it's because [`render-tex.R` knits each chapter in a new environment](https://github.com/hadley/ggplot2-book/blob/ab249951d3a8a7abaf140e392464cc77eaf7d589/render-tex.R#L37)?

**Comment by hadley** [comment]
I still get the same problem if I remove that argument :/

**Comment by cpsievert** [comment]
Not totally sure why, but if I switching from `new.env()` to `globalenv()` seems to fix it.
