### ISSUE TITLE
Can't build, Mac OS X 10.10.4, R 3.2.1

### ISSUE THREAD

**Issue by JerryWho** [hadley/ggplot2-book#60]
I can't build the book using Mac OS X Yosemite 10.10.4 with the latest R-version 3.2.1.
I always get this error:
```
processing file: duplication.rmd
Quitting from lines 36-48 (duplication.rmd) 
Error in do.call("layer", list(mapping = mapping, data = data, stat = stat,  : 
  could not find function "alpha"
Calls: mapply ... geom_smooth -> <Anonymous> -> <Anonymous> -> do.call
Execution halted
make: *** [book/tex/duplication.tex] Error 1

Exited with status 2.
```
So I've change this file to call ```scales::alpha```. But than I run into the next error.

```
Rscript render-tex.R extending.rmd
Warning message:
Detected a difference in actual and expected chapters.
Error in mapply(bumper, bump_n, chap_ord[chap_id], SIMPLIFY = FALSE) :
  zero-length inputs cannot be mixed with those of non-zero length
Execution halted
make: *** [book/tex/extending.tex] Error 1
```
I don't see what's wrong. So my question is which versions of R and R-packages do I need to compile the book using Mac OS X Yosemite?

**Comment by hadley** [comment]
You need the dev version of ggplot2

**Comment by JerryWho** [comment]
Okay, using dev version (I hope you mean the github version 1.0.1.9000) fixes the first error. But the next one (with ```Rscript render-tex.R extending.rmd```) does still occur. When touching ```book/tex/extending.tex``` to fix this one the next one is just a few seconds away:
```
Rscript render-tex.R mastery.rmd
Warning message:
Detected a difference in actual and expected chapters.


processing file: mastery.rmd
geom_smooth: method="auto" and size of largest group is <1000, so using loess. Use 'method = x' to change the smoothing method.
geom_smooth: method="auto" and size of largest group is <1000, so using loess. Use 'method = x' to change the smoothing method.
Quitting from lines 200-208 (mastery.rmd)
Error in eval(expr, envir, enclos) :
  could not find function "draw_legends"
Calls: mapply ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted
make: *** [book/tex/mastery.tex] Error 1
```
So which environment do I need for compiling the book? Shall I try using Linux? There must be a way to compile it.

**Comment by cpsievert** [comment]
@JerryWho changes just made in 1f3cf3e284e1075ed33c621ba4be2da4541a7c27 should fix that problem
