### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by alcy** [hadley/ggplot2-book#61]
Hello, I am getting the following error on Mac Yosemite using RStudio and R (version 3.2.0). The dev versions of ggplot2 and dplyr are installed apart from the other dependencies. The system has MacTex distribution with the Inconsolata font and the hyperref package installed.  
>Error in mapply(bumper, bump_n, chap_ord[chap_id], SIMPLIFY = FALSE) : 
 > zero-length inputs cannot be mixed with those of non-zero length
>Execution halted
>make: *** [book/tex/extending.tex] Error 1

>Exited with status 2.

**Comment by cpsievert** [comment]
Change I _just_ made in ea62076b5e544fb5f78d79b8ec695946697e4f6a should fix that problem
