### ISSUE TITLE
Build fails at Undefined control sequence \tightlist

### ISSUE THREAD

**Issue by alcy** [hadley/ggplot2-book#62]
Hello, while rendering qplot.rmd, the build fails at line 145: 
> [13] [14] <use  "figures/qplotqscatter-1.pdf" > [15]
> ! Undefined control sequence.
> l.145 \tightlist

I found a few related issue reports [elsewhere] (https://github.com/rstudio/rmarkdown/issues/439), but apparently the issue is fixed in pandoc 1.14. I am using pandoc 1.15 and MacTex 2015.

**Comment by hadley** [comment]
Works for me now.
