### ISSUE TITLE
Opening section that describes plots in terms of geoms, aesthetics, etc?

### ISSUE THREAD

**Issue by rpruim** [hadley/ggplot2-book#64]
When we teach ggplot2 in our workshops, we find it useful to begin with some exercises where people look at existing plots and identify the elements in terms of the grammar of graphics.  Basically we teach the abstract grammar first and then the ggplot2 implementation.

Once people can use the grammar of graphics to describe a plot, it is pretty easy to get them to translate into ggplot2 code.  But it isn't natural for some at first.  The distinction between setting and mapping and the name aesthetic are two things that trip people up.

Example plots can come from ggplot2 or from any source.  (NY Times is a good source).

If your book will contain stuff of dplyr/tidyr, we have found the phrase glyph-ready data to help people.  Perhaps you will want to replace "glyph" with something that sounds more ggplot2-ish.

**Comment by hadley** [comment]
I have some challenges along those lines I the second chapter - I prefer to start with code, but I can understand why you might like theory first
