### ISSUE TITLE
Table of contents (undefined control sequence)

### ISSUE THREAD

**Issue by Hjalt** [hadley/ggplot2-book#67]
When trying to build the book in RStudio, I run into the following errror:

```
! Undefined control sequence.
<argument> ...@edef \Hy@testname {\Hy@tocdestname 
                                                  }\ifx \Hy@testname \@empty...
l.107  \tableofcontents
```

If I comment out  `\tableofcontents`in `ggplot2-book.tex` the book compiles OK.

Any thoughts?

**Comment by hadley** [comment]
Fixed now

**Comment by drvinceknight** [comment]
@hadley this is a situation best described by:

![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

I don't suppose you remember what you did to fix this? (I'm dealing with the same error message)

**Comment by drvinceknight** [comment]
No problem I thought as much :)
