### ISSUE TITLE
problem at line 250 in tidy-data.rmd

### ISSUE THREAD

**Issue by jrminter** [hadley/ggplot2-book#78]
Line 250:
```
bpd_2 <- separate(bpd_1, bp, c("sys", "dia"), "/")
```

produces error:

```
Error: Values not split into 2 pieces at 6, 9
```

Both these have `NA` for bp. Do you intend to add `extra='drop'` ?

**Comment by cpsievert** [comment]
We neglected to mention in the README that you currently need the dev version of tidyr...
