### ISSUE TITLE
compilation issue on Mac

### ISSUE THREAD

**Issue by mkborregaard** [hadley/ggplot2-book#82]
I am trying to compile the book - I am on Mac OS X Yosemite, using R 3.1.3, all packages updated and all dependencies installed. Unfortunately it fails with this error:
'''zn11265:ggplot2-book michael$ make
Rscript book/render-tex.R introduction.rmd
Quitting from lines 182-183 (introduction.rmd) 
Fejl i desc$Priority : $ operator is invalid for atomic vectors
Calls: <Anonymous> ... <Anonymous> -> structure -> package_info -> vapply -> FUN
Execution halted
make: *** [book/tex/introduction.tex] Error 1'''
can you direct me to what I am doing wrong?

**Comment by hadley** [comment]
Should be fixed now

**Comment by EmilRehnberg** [comment]
I possibly have the same issue. I do get almost an identical error on El Capitan with R version 3.2.2. 
```
> make
Rscript book/render-tex.R introduction.rmd
Quitting from lines 180-181 (introduction.rmd)
Error in desc$Priority : $ operator is invalid for atomic vectors
Calls: <Anonymous> ... <Anonymous> -> structure -> package_info -> vapply -> FUN
Execution halted
make: *** [book/tex/introduction.tex] Error 1
```

**Comment by py9mrg** [comment]
Install the packages BH, that seems to cure the problem.
