### ISSUE TITLE
Nice that qplot is gone

### ISSUE THREAD

**Issue by dmenne** [hadley/ggplot2-book#83]
Praise for removing qplot in the intro! I am quite good at lattice, but I needed long time to get into ggplot because qplot was simply too confusing, and the book had to many qplot examples. I know, it was meant as a bridge from standard graphics when it was introduced, and it was an interesting experience that this bridge acted as a barbwire wall.

**Comment by Robinlovelace** [comment]
I agree.

**Comment by hadley** [comment]
Glad you like it :)
