### ISSUE TITLE
PDF Latex Make Issue

### ISSUE THREAD

**Issue by abresler** [hadley/ggplot2-book#89]
Trying to run the make code and I run into this error

```
Latexmk: This is Latexmk, John Collins, 10 Nov 2013, version: 4.39.
**** Report bugs etc to John Collins <collins at phys.psu.edu>. ****
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'xelatex  -interaction=batchmode -recorder  "ggplot2-book.tex"'
------------
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Missing input file: 'framed.sty' from line
  '! LaTeX Error: File `framed.sty' not found.'
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
make: *** [book/ggplot2-book.pdf] Error 12
___________________    | ~/Desktop/Github/alex_learning_r/Alex_Learning_R/ggplot2/ggplot2-book @ Alexs-MacBook-Pro (alexbresler) 
```

Any suggestions would be appreciated!

**Comment by hadley** [comment]
I'd say you need to install the framed latex packae.

**Comment by chuckwondo** [comment]
Hi @hadley, thanks for making your book publicly available here (and thanks for all of your fantastic libraries too)! Would it be possible to add details to `README.md` regarding such steps? Would you like a pull-request for such updates?

Here's are the additional steps I found necessary to get farther along in making the book, but are not explicit in the `README.md` (and thus may not be obvious to those of us who don't use LaTeX):

1. Run `library(devtools)`
1. Install a LaTeX system (I installed BasicTeX on Mac OS X)
1. Run the following 2 commands from Terminal to install the `framed` LaTeX package:
   1. `sudo tlmgr update --self`
   1. `sudo tlmgr install framed`

Note, however, that although I have gotten past several errors with these additional steps, I still run into errors. I will open a new issue with the latest errors that I'm seeing.

**Comment by chuckwondo** [comment]
I see that my latest error has to do with the Inconsolata font, which I have so far been unable to install successfully. I'll work on getting that sorted out, which will hopefully be the last of the problems I encounter.

**Comment by hadley** [comment]
The problem is that the latex instructions vary so much from platform to platform. I'd be happy to accept a PR that listed packages that you might need to install though.
