### ISSUE TITLE
Figure out reference weirdness

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#96]
e.g. in the toolbox chapter we get "Carr, D. B., R. J. Littlefield, W. L. Nicholson, and J. S. Littlefield" - note the inconsistent last name-first name ordering.

Any ideas @cpsievert ?

**Comment by cpsievert** [comment]
Huh, strange, haven't run across this before...

**Comment by hadley** [comment]
@jjallaire any idea where to start debugging this problem? I'm relying on the citation stuff built into Rmarkdown.

**Comment by jjallaire** [comment]
Unfortunately I don't (don't have any experience with or knowledge of pandoc citations). Maybe @yihui does?

**Comment by yihui** [comment]
I guess it might be a bug of Pandoc. I observed this long time ago, but didn't report to Pandoc, e.g. see the first reference here http://yihui.name/Rd2roxygen/ "Wickham, Hadley, and Yihui Xie".

I think it will be more reliable to process citations through bibtex when you want PDF output, i.e. do not use `--filter pandoc-citeproc` but use `--natbib` instead. You will have compile the .tex output to PDF by yourself in this case. When `--natbib` is used, `pandoc-citeproc` won't work.

Actually it may be a better idea to change `rmarkdown::pdf_document()` to use this approach: first generate the .tex output using --natbib, then convert .tex to PDF. Currently we are doing .md -> .tex and .md -> .pdf in two passes.

There is also a `--biblatex` option in Pandoc, but I'm only familiar with `--natbib`.
