### ISSUE TITLE
layers.rmd -- lines 20-22 Error: No layers in plot

### ISSUE THREAD

**Issue by jtr13** [hadley/ggplot2-book#98]
When I tried to make the book I got the following error:

Quitting from lines 20-22 (layers.rmd) 
Error: No layers in plot
Execution halted
make: *** [book/tex/layers.tex] Error 1

Joyce Robbins

**Comment by hadley** [comment]
You need the dev version of ggplot2.

**Comment by jtr13** [comment]
Aha, thx.
